package drawer_templates

const (
	NetworkStatsDownload      = "^c%s^^b%s^^c%s^ 󰄼 ^c%s^^b%s^ %s"
	NetworkStatsUpload        = " ^b%s^^c%s^ 󰄿 ^c%s^^b%s^ %s "
	CpuData                   = "^c%s^^c%s^^b%s^ 󰘚 %d "
	CpuTemp                   = "^c%s^^c%s^^b%s^ 󰔄 %s "
	MemoryUsage               = "^c%s^^b%s^^c%s^^b%s^ 󰍛 %s "
	Brightness                = "^c%s^^b%s^^c%s^^b%s^ 󱩎 %d"
	VolumeMuted               = "^c%s^^b%s^^c%s^^b%s^ 󰝟 "
	VolumePart0               = "󰝞"
	VolumePartGT0             = "󰕿"
	VolumePartGT30            = "󰖀"
	VolumePartGT70            = "󰕾"
	Volume                    = "^c%s^^b%s^^c%s^^b%s^ %s %d"
	NetworkConnectionWired    = "^c%s^^b%s^^c%s^ 󰌘 %s "
	NetworkConnectionWireless = "^b%s^^c%s^ 󰖩 %s "
	BatPartFull               = "󰁹"
	BatPartDischarging        = ""
	BatPartCharging           = "󰂄"
	BatPartNotCharging        = "󱧥"
	BatPartUnknown            = "󱟟"
	BatPartUndefined          = "Undefined"
	BatPartWarningSymbol      = "󱃍"
	BatPartWarning            = "^c%s^^b%s^ %s"
	BatPartStatus             = "^c%s^^c%s^^b%s^ %s"
	Bat                       = "%s%s%d%% "
	KeyboardLayout            = "^c%s^^b%s^^c%s^^b%s^ 󰌌 %s "
	Clock                     = "^c%s^^c%s^^b%s^ 󱑍 %s "
	NotificationsDisabled     = "^c%s^^c%s^^b%s^  󰂛 "
)
